# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cht/cpp/thesnake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cht/cpp/thesnake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cht/cpp/thesnake/CMakeFiles /home/cht/cpp/thesnake//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cht/cpp/thesnake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named code_check

# Build rule for target.
code_check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 code_check
.PHONY : code_check

# fast build rule for target.
code_check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/code_check.dir/build.make CMakeFiles/code_check.dir/build
.PHONY : code_check/fast

#=============================================================================
# Target rules for targets named Demo

# Build rule for target.
Demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Demo
.PHONY : Demo

# fast build rule for target.
Demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/build
.PHONY : Demo/fast

#=============================================================================
# Target rules for targets named Demo_autogen

# Build rule for target.
Demo_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Demo_autogen
.PHONY : Demo_autogen

# fast build rule for target.
Demo_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo_autogen.dir/build.make CMakeFiles/Demo_autogen.dir/build
.PHONY : Demo_autogen/fast

Demo_autogen/mocs_compilation.o: Demo_autogen/mocs_compilation.cpp.o
.PHONY : Demo_autogen/mocs_compilation.o

# target to build an object file
Demo_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/Demo_autogen/mocs_compilation.cpp.o
.PHONY : Demo_autogen/mocs_compilation.cpp.o

Demo_autogen/mocs_compilation.i: Demo_autogen/mocs_compilation.cpp.i
.PHONY : Demo_autogen/mocs_compilation.i

# target to preprocess a source file
Demo_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/Demo_autogen/mocs_compilation.cpp.i
.PHONY : Demo_autogen/mocs_compilation.cpp.i

Demo_autogen/mocs_compilation.s: Demo_autogen/mocs_compilation.cpp.s
.PHONY : Demo_autogen/mocs_compilation.s

# target to generate assembly for a file
Demo_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/Demo_autogen/mocs_compilation.cpp.s
.PHONY : Demo_autogen/mocs_compilation.cpp.s

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/mainwindow.o: source/mainwindow.cpp.o
.PHONY : source/mainwindow.o

# target to build an object file
source/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/mainwindow.cpp.o
.PHONY : source/mainwindow.cpp.o

source/mainwindow.i: source/mainwindow.cpp.i
.PHONY : source/mainwindow.i

# target to preprocess a source file
source/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/mainwindow.cpp.i
.PHONY : source/mainwindow.cpp.i

source/mainwindow.s: source/mainwindow.cpp.s
.PHONY : source/mainwindow.s

# target to generate assembly for a file
source/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/mainwindow.cpp.s
.PHONY : source/mainwindow.cpp.s

source/snake.o: source/snake.cpp.o
.PHONY : source/snake.o

# target to build an object file
source/snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/snake.cpp.o
.PHONY : source/snake.cpp.o

source/snake.i: source/snake.cpp.i
.PHONY : source/snake.i

# target to preprocess a source file
source/snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/snake.cpp.i
.PHONY : source/snake.cpp.i

source/snake.s: source/snake.cpp.s
.PHONY : source/snake.s

# target to generate assembly for a file
source/snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Demo.dir/build.make CMakeFiles/Demo.dir/source/snake.cpp.s
.PHONY : source/snake.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Demo_autogen"
	@echo "... code_check"
	@echo "... format"
	@echo "... Demo"
	@echo "... Demo_autogen/mocs_compilation.o"
	@echo "... Demo_autogen/mocs_compilation.i"
	@echo "... Demo_autogen/mocs_compilation.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/mainwindow.o"
	@echo "... source/mainwindow.i"
	@echo "... source/mainwindow.s"
	@echo "... source/snake.o"
	@echo "... source/snake.i"
	@echo "... source/snake.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

